### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [JanekAgent/oop-put-course#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Rename file to task1.cpp
- [ ] Don't use polish language 
- [ ] Format code [properly](https://google.github.io/styleguide/cppguide.html)
